name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["cdcent/proximity-tool"]
assignees:
  - s5rockhill
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Package version
      description: What version of our software are you running?
      options:
        - 1.0.0 (Default)
      default: 0
    validations:
      required: true
  - type: input
    id: RVersion
    attributes:
      label: R Version
      description: Tell us which version(s) of R are you using. Include all versions you've tested (e.g., 4.4.2;4.3.3).
    validations:
      required: true
  - type: dropdown
    id: os
    attributes: 
      label: Operating system
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
